version: '2.3'
services:
   node:
      container_name: hashcatnode
      environment:
         - NVIDIA_VISIBLE_DEVICES=all
         - HASHCATNODE_USERNAME=test
         - HASHCATNODE_HASH=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
      build: .
      ports:
         - "9999:9999"
      deploy:
        resources:
          reservations:
            devices:
            - driver: nvidia
              capabilities: [gpu]
